import { Project, TeamMember, IdeaCard } from '../types';

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'user-1',
    name: 'Zogo',
    username: 'zogo',
    role: 'Co-Founder & CEO',
    roleType: 'founder',
    avatar: '👨‍💼',
    color: '#0052CC',
    passcode: 'zogo2026',
    mustResetPasscode: true,
    email: 'zogo@achigo.tech',
  },
  {
    id: 'user-2',
    name: 'Achiri',
    username: 'achiri',
    role: 'Co-Founder & Product Architect',
    roleType: 'founder',
    avatar: '🚀',
    color: '#00875A',
    passcode: 'achiri2026',
    mustResetPasscode: true,
    email: 'achiri@achigo.tech',
  },
  {
    id: 'user-3',
    name: 'David Miller',
    username: 'david',
    role: 'Tech Lead / Engineer',
    roleType: 'lead',
    avatar: '🧑‍🔬',
    color: '#6554C0',
    passcode: 'david123',
    mustResetPasscode: true,
    email: 'david@achigo.tech',
  },
  {
    id: 'user-4',
    name: 'Elena Rostova',
    username: 'elena',
    role: 'UX / Product Designer',
    roleType: 'member',
    avatar: '🎨',
    color: '#FF5630',
    passcode: 'elena123',
    mustResetPasscode: true,
    email: 'elena@achigo.tech',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    keyPrefix: 'AI',
    name: 'PulseAI - Voice Copilot',
    description: 'Real-time conversational voice assistant for enterprise operations & meeting intelligence.',
    color: '#0052CC',
    icon: 'Bot',
    createdAt: '2026-08-01T10:00:00.000Z',
  },
  {
    id: 'proj-2',
    keyPrefix: 'FIN',
    name: 'NovaPay - Borderless Vault',
    description: 'Multi-currency digital business banking platform with real-time FX & automated treasury.',
    color: '#00875A',
    icon: 'Wallet',
    createdAt: '2026-08-05T12:00:00.000Z',
  },
  {
    id: 'proj-3',
    keyPrefix: 'FLOW',
    name: 'SyncFlow - Startup PM Suite',
    description: 'Next-generation agile product management suite for AchiGO projects.',
    color: '#6554C0',
    icon: 'Layers',
    createdAt: '2026-08-10T09:30:00.000Z',
  },
];

export const INITIAL_IDEAS: IdeaCard[] = [
  {
    id: 'idea-1',
    issueKey: 'AI-101',
    projectId: 'proj-1',
    title: 'Instant Meeting Action Item Auto-Extraction',
    issueType: 'feature',
    stage: 'prompt_creation',
    priority: 'critical',
    summary: 'Automatically parse audio transcripts during live meetings and generate assigned Jira tickets without human note-taking.',
    targetAudience: 'Product managers, founders, and engineering managers who attend 5+ meetings daily.',
    painPoint: 'Founders and PMs spend 30-45 minutes after every call writing follow-ups and assigning tasks. Critical action items are routinely lost or misremembered.',
    proposedSolution: 'Stream live audio chunks to the AI listener. As tasks are verbally agreed, trigger a non-intrusive floating HUD displaying drafted tickets. With 1-click confirmation, the items sync directly to the project Kanban.',
    valueProposition: 'Saves 3 hours per week per team member and eliminates lost commitments across client calls.',
    successCriteria: [
      'Identifies action items with >92% accuracy from conversation stream',
      'Allows 1-click team member assignment and due-date parsing',
      'Syncs to project backlog within 3 seconds',
      'Provides privacy filter to scrub sensitive financial/credential mentions',
    ],
    customPromptNotes: 'Instruct dev team to structure the Web Audio API stream with 5-second chunking and use standard TypeScript types for action item cards.',
    targetAiTool: 'antigravity',
    manualTests: [
      { id: 't-1', scenario: 'Simulate 2-minute meeting transcript with 3 clear action items', expectedResult: 'All 3 items extracted into UI HUD within 2 seconds', passed: true, testedBy: 'Achiri' },
      { id: 't-2', scenario: 'Check privacy scrubber on spoken credit card or API key strings', expectedResult: 'Sensitive numbers masked with **** in ticket draft', passed: false, notes: 'Need regex validation' },
      { id: 't-3', scenario: 'Click Sync to Backlog on drafted ticket', expectedResult: 'Card instantly appears in project Backlog view', passed: true, testedBy: 'Zogo' },
    ],
    founderScore: {
      userImpact: 5,
      marketUrgency: 5,
      implementationSimplicity: 4,
      strategicFit: 5,
    },
    authorId: 'user-2',
    assigneeId: 'user-3',
    votes: {
      'user-1': { memberId: 'user-1', status: 'approved', comment: 'Game changer for our sales pipeline!', updatedAt: '2026-08-15T14:20:00Z' },
      'user-2': { memberId: 'user-2', status: 'approved', comment: 'Clear user demand from our beta waitlist.', updatedAt: '2026-08-15T14:22:00Z' },
      'user-3': { memberId: 'user-3', status: 'approved', comment: 'Clean to build with web speech API + LLM stream.', updatedAt: '2026-08-15T15:00:00Z' },
      'user-4': { memberId: 'user-4', status: 'approved', comment: 'UX mockup is ready and tested.', updatedAt: '2026-08-15T15:30:00Z' },
    },
    comments: [
      {
        id: 'c-1',
        memberId: 'user-1',
        text: 'Let us make sure we support both English and European accents well.',
        createdAt: '2026-08-15T14:21:00Z',
      },
    ],
    tags: ['AI Audio', 'Productivity', 'Enterprise'],
    createdAt: '2026-08-14T09:00:00Z',
    updatedAt: '2026-08-15T15:30:00Z',
  },
  {
    id: 'idea-2',
    issueKey: 'AI-102',
    projectId: 'proj-1',
    title: 'Smart Voice Command Security Verification Bug',
    issueType: 'bug',
    stage: 'refinement',
    priority: 'high',
    summary: 'Biometric voice verification occasionally fails on noisy mobile microphones causing command execution timeouts.',
    targetAudience: 'Startup founders on mobile or driving managing cloud deployments.',
    painPoint: 'Voice recognition fails in moving vehicles resulting in 504 timeout errors without falling back to secondary PIN verification.',
    proposedSolution: 'Add noise-canceling preprocessor on audio stream and fallback to biometric touch/PIN prompt when SNR is low.',
    valueProposition: 'Ensures 99.9% reliability for mission-critical mobile voice commands.',
    successCriteria: [
      'Understands voice commands with noisy background tolerance',
      'Requires secondary verbal confirmation or PIN for destructive actions',
      'Logs every command in audit trail with timestamp',
    ],
    founderScore: {
      userImpact: 4,
      marketUrgency: 4,
      implementationSimplicity: 3,
      strategicFit: 4,
    },
    authorId: 'user-1',
    assigneeId: 'user-1',
    votes: {
      'user-1': { memberId: 'user-1', status: 'approved', comment: 'Critical to fix before release.', updatedAt: '2026-08-16T10:00:00Z' },
      'user-2': { memberId: 'user-2', status: 'approved', comment: 'Agreed, high friction bug.', updatedAt: '2026-08-16T10:30:00Z' },
      'user-3': { memberId: 'user-3', status: 'needs_discussion', comment: 'Need to review security precautions against accidental voice triggers.', updatedAt: '2026-08-16T11:15:00Z' },
      'user-4': { memberId: 'user-4', status: 'pending', updatedAt: '2026-08-16T09:00:00Z' },
    },
    comments: [
      {
        id: 'c-3',
        memberId: 'user-3',
        text: 'Security risk on accidental voice triggers. We need mandatory double confirmation PIN or biometric touch.',
        createdAt: '2026-08-16T11:16:00Z',
      },
    ],
    tags: ['Security', 'BugFix', 'Mobile'],
    createdAt: '2026-08-16T08:30:00Z',
    updatedAt: '2026-08-16T11:16:00Z',
  },
  {
    id: 'idea-3',
    issueKey: 'AI-103',
    projectId: 'proj-1',
    title: 'Custom Persona & Tone Tuning for Voice Reps',
    issueType: 'improvement',
    stage: 'backlog',
    priority: 'medium',
    summary: 'Improve voice cadence, energy level, and vocabulary style customization options for brand alignment.',
    targetAudience: 'Brands wanting a distinctive corporate persona.',
    painPoint: 'Default voice agents sound generic, robotic, or mismatch the brand aesthetic.',
    proposedSolution: 'Interactive slider matrix in settings: Formal <-> Casual, Empathetic <-> Direct, Fast <-> Measured, with instant preview audio.',
    valueProposition: 'Increases brand identity retention and customer rapport by 40%.',
    successCriteria: [
      'Real-time voice synthesis preview in under 1 second',
      'Presets for Tech Support, Executive Concierge, Sales SDR, and Friendly Coach',
    ],
    founderScore: {
      userImpact: 4,
      marketUrgency: 2,
      implementationSimplicity: 4,
      strategicFit: 3,
    },
    authorId: 'user-4',
    votes: {
      'user-1': { memberId: 'user-1', status: 'pending', updatedAt: '2026-08-17T09:00:00Z' },
      'user-2': { memberId: 'user-2', status: 'pending', updatedAt: '2026-08-17T09:00:00Z' },
      'user-3': { memberId: 'user-3', status: 'pending', updatedAt: '2026-08-17T09:00:00Z' },
      'user-4': { memberId: 'user-4', status: 'approved', comment: 'Design system spec is ready.', updatedAt: '2026-08-17T09:10:00Z' },
    },
    comments: [],
    tags: ['Brand', 'UI/UX', 'Voice'],
    createdAt: '2026-08-17T09:00:00Z',
    updatedAt: '2026-08-17T09:10:00Z',
  },
  {
    id: 'idea-4',
    issueKey: 'AI-104',
    projectId: 'proj-1',
    title: 'Autonomous Daily Standup Audio Digest',
    issueType: 'feature',
    stage: 'manual_testing',
    priority: 'high',
    summary: 'Gathers Git commits and Jira cards to produce a 60-second audio standup update every morning.',
    targetAudience: 'Engineering leaders and remote startup teams.',
    painPoint: 'Traditional 30-minute daily standups drain team momentum and disrupt deep focus states.',
    proposedSolution: 'Aggregates yesterday merged PRs, active blockers, and produces an async digest with clickable show notes.',
    valueProposition: 'Replaces synchronous 30-minute meetings with a 2-minute high-fidelity overview.',
    successCriteria: [
      'Delivered to Slack/Discord/Email at 9:00 AM daily',
      'Highlights blockers in high-visibility alert banner',
      'Interactive transcription with direct PR links',
    ],
    manualTests: [
      { id: 't-4', scenario: 'Ingest sample commit log with 8 PRs and 2 blockers', expectedResult: 'Audio synthesis summarizes the 2 blockers in the first 15 seconds', passed: true, testedBy: 'David Miller' },
      { id: 't-5', scenario: 'Test audio playback across Chrome, Safari, and Mobile iOS', expectedResult: 'Crisp audio playback with pause/resume and 1.5x speed controls', passed: true, testedBy: 'Elena Rostova' },
      { id: 't-6', scenario: 'Click direct PR link inside the interactive show notes', expectedResult: 'Opens target repository URL in a new tab without session loss', passed: true, testedBy: 'Achiri' },
    ],
    founderScore: {
      userImpact: 5,
      marketUrgency: 4,
      implementationSimplicity: 4,
      strategicFit: 5,
    },
    authorId: 'user-3',
    assigneeId: 'user-3',
    votes: {
      'user-1': { memberId: 'user-1', status: 'approved', comment: 'All in! Saves so much time.', updatedAt: '2026-08-12T10:00:00Z' },
      'user-2': { memberId: 'user-2', status: 'approved', comment: 'Tested prototype internally, loved it.', updatedAt: '2026-08-12T10:05:00Z' },
      'user-3': { memberId: 'user-3', status: 'approved', comment: 'Build complete. Now in QA testing!', updatedAt: '2026-08-12T10:10:00Z' },
      'user-4': { memberId: 'user-4', status: 'approved', comment: 'Audio player UI verified.', updatedAt: '2026-08-12T10:15:00Z' },
    },
    comments: [],
    tags: ['Async', 'DevTools', 'Agile'],
    createdAt: '2026-08-11T09:00:00Z',
    updatedAt: '2026-08-12T10:15:00Z',
  },
  {
    id: 'idea-5',
    issueKey: 'AI-105',
    projectId: 'proj-1',
    title: 'Multi-lingual Realtime Voice Translation (14 Languages)',
    issueType: 'feature',
    stage: 'shipped',
    priority: 'critical',
    summary: 'Sub-500ms bidirectional speech-to-speech translation during live customer support sessions.',
    targetAudience: 'Global tech support teams and multinational sales organizations.',
    painPoint: 'Hiring native support agents in 10+ languages is cost prohibitive for early-stage tech companies.',
    proposedSolution: 'Zero-latency neural translation layer retaining speaker voice timbre and natural inflection.',
    valueProposition: 'Instant global support coverage with a 90% reduction in staffing overhead.',
    successCriteria: [
      'Latency under 500 milliseconds across EU/US/APAC endpoints',
      'Maintains speaker emotional tone and confidence',
      'Automatic fallback to text subtitles on low bandwidth',
    ],
    manualTests: [
      { id: 't-7', scenario: 'Simultaneous conversation English <-> Japanese', expectedResult: 'Zero word truncation and accurate translation', passed: true, testedBy: 'Zogo' },
      { id: 't-8', scenario: 'Simulate high packet loss network environment', expectedResult: 'Subtitles display immediately with reconnect banner', passed: true, testedBy: 'David Miller' },
    ],
    founderScore: {
      userImpact: 5,
      marketUrgency: 5,
      implementationSimplicity: 3,
      strategicFit: 5,
    },
    authorId: 'user-1',
    assigneeId: 'user-3',
    votes: {
      'user-1': { memberId: 'user-1', status: 'approved', updatedAt: '2026-08-02T10:00:00Z' },
      'user-2': { memberId: 'user-2', status: 'approved', updatedAt: '2026-08-02T10:00:00Z' },
      'user-3': { memberId: 'user-3', status: 'approved', updatedAt: '2026-08-02T10:00:00Z' },
      'user-4': { memberId: 'user-4', status: 'approved', updatedAt: '2026-08-02T10:00:00Z' },
    },
    comments: [],
    tags: ['Global', 'AI Core', 'Shipped'],
    createdAt: '2026-08-01T12:00:00Z',
    updatedAt: '2026-08-08T18:00:00Z',
  },
];
